twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/vendor/easycorp/easyadmin-bundle/templates': 'EasyAdmin'
    globals:

when@test:
    twig:
        strict_variables: true
