framework:
    validation:
        auto_mapping:
            App\Entity\: []  # Enables validator auto-mapping for all entities in the App\Entity namespace.

when@test:
    framework:
        validation:
            not_compromised_password: false
